application:
  name: zgit

ssh:
  server:
    port: 2222
  proxy:
    port: 2222

http:
  port: 80

lfs:
  enabled: true

app:
  url: http://127.0.0.1
  lang: en-US
  corpId: zexin

xorm:
  dataSourceName: root:root@tcp(127.0.0.1:3306)/hhhh?charset=utf8
